name: Run API Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-api:
    runs-on: ubuntu-latest

    env:
      MONGODB_URI: mongodb+srv://tranhantgdd2020:Mst2Lf0hAEr5CDPo@cluster0.cdokk.mongodb.net/ContactBook/?retryWrites=true&w=majority&appName=Cluster0
      PORT: 3000 
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Newman & wait-on
      run: npm install -g newman wait-on

    - name: Install project dependencies
      run: npm install

    - name: Start backend server
      run: npm start &
    

    - name: Run Postman Tests
      run: newman run tests/collection.json -e tests/env.json
