name: Run API Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-api:
    runs-on: ubuntu-latest

    env:
      MONGODB_URI: mongodb+srv://tranhantgdd2020:Mst2Lf0hAEr5CDPo@cluster0.cdokk.mongodb.net/ContactBook/?retryWrites=true&w=majority&appName=Cluster0
      PORT: 3000 
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Newman & wait-on
      run: npm install -g newman wait-on

    - name: Install project dependencies
      run: npm install

    - name: Start backend server
      run: npm start &
    

    - name: Install Postman CLI
      run: |
        curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
    - name: Login to Postman CLI
      run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
    - name: Run API tests
      run: |
        postman collection run "${{ github.workspace }}/postman/collections/PTUDW.json" -e "37602483-0497d922-7b8c-4e92-ae22-7c8f8f8e3ada"
